# Generated by Django 5.0.1 on 2024-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='fechado',
            field=models.BooleanField(default=False),
        ),
    ]
