# Generated by Django 5.0.1 on 2024-07-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0002_ordem_fechado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='fechado',
        ),
    ]
