# Generated by Django 5.0.7 on 2024-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='codigo_sap',
        ),
        migrations.RemoveField(
            model_name='material',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='nome',
        ),
        migrations.AlterField(
            model_name='material',
            name='criticidade',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=10, null=True),
        ),
    ]
