# Generated by Django 5.0.1 on 2024-07-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0002_item_remove_material_codigo_sap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spare.item'),
        ),
    ]
