# Generated by Django 5.0.1 on 2024-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0003_material_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
