# Generated by Django 5.0.1 on 2024-07-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0004_material_codigo_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='criticidade',
            field=models.ForeignKey(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='spare.criticidade'),
        ),
    ]
