# Generated by Django 5.0.1 on 2024-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0005_alter_material_criticidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='criticidade',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=10, null=True),
        ),
    ]
