# Generated by Django 5.0.1 on 2024-08-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('spare', '0006_alter_material_criticidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.setor'),
        ),
    ]
