# Generated by Django 5.0.1 on 2024-08-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0007_categoria_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descricao',
            new_name='descricao_sap',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='nome_sap',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='item',
            new_name='item_sap',
        ),
    ]
