# Generated by Django 5.0.1 on 2024-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0008_rename_descricao_item_descricao_sap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='apelido_linha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='descricao_fornecedor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
