# Generated by Django 5.0.1 on 2024-08-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0009_material_apelido_linha_material_descricao_fornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='item_sap',
            new_name='item',
        ),
    ]
