# Generated by Django 5.0.1 on 2024-08-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0010_rename_item_sap_material_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.item'),
        ),
    ]
