# Generated by Django 5.0.1 on 2024-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0011_alter_material_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
