# Generated by Django 5.0.1 on 2024-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0012_alter_material_codigo_sap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='setor',
        ),
        migrations.AlterField(
            model_name='material',
            name='apelido_linha',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='localizacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
