# Generated by Django 5.1.5 on 2025-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_tecnicos_setor_tecnicos_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnicos',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='tecnicos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_tecnicos/'),
        ),
    ]
