# Generated by Django 5.1.5 on 2025-01-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_alter_tecnicos_options_tecnicos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnicos',
            name='foto',
        ),
    ]
