# Generated by Django 5.0.1 on 2024-07-24 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0002_tecnicos_setor_tecnicos_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ordem', models.CharField(max_length=100)),
                ('loc_instalacao', models.CharField(max_length=100)),
                ('denominacao', models.CharField(max_length=100)),
                ('nota', models.TextField(default='Default note value')),
                ('ordem', models.CharField(max_length=100, unique=True)),
                ('texto_breve', models.CharField(max_length=200)),
                ('liberacao_real', models.DateTimeField(blank=True, null=True)),
                ('data_base_inic', models.DateField(blank=True, null=True)),
                ('data_base_fim', models.DateField(blank=True, null=True)),
                ('inic_real_hr', models.DateTimeField(blank=True, null=True)),
                ('fim_real_hr', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('centro_custo', models.CharField(max_length=100)),
                ('total_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_sistema', models.CharField(max_length=100)),
                ('status_preventiva', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tempo_execucao', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('lancado_no_sap', models.BooleanField(default=False)),
                ('centro_trabalho_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventivas', to='tecnicos.tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Atividade')),
                ('preventivas', models.ManyToManyField(blank=True, related_name='atividades', to='preventiva.preventiva')),
                ('tarefas', models.ManyToManyField(blank=True, related_name='atividades', to='preventiva.tarefa')),
            ],
        ),
    ]
