# Generated by Django 5.0.1 on 2024-07-23 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoChecklist',
            fields=[
                ('letra', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('componente', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('tipo_problema', models.CharField(choices=[('Mecânico', 'Mecânico'), ('Eletrônico', 'Eletrônico')], default='Mecânico', max_length=20)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.area')),
                ('criticidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.criticidade')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.linha')),
                ('opcoes_checklist', models.ManyToManyField(to='solicitacao.opcaochecklist')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.turno')),
            ],
        ),
    ]
