# Generated by Django 5.0.1 on 2024-08-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_solicitacao_setor_solicitacao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='user',
        ),
    ]
