# Generated by Django 5.0.1 on 2024-08-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_solicitacao_setor_solicitacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status_solicitacao',
            field=models.BooleanField(default=True),
        ),
    ]
