# Generated by Django 5.0.1 on 2024-08-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_solicitacao_status_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='status_solicitacao',
        ),
    ]
