# Generated by Django 5.0.1 on 2024-07-24 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.setor'),
        ),
    ]
