# Generated by Django 5.0.1 on 2024-07-24 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipamento', '0002_equipamento_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.setor'),
        ),
        migrations.AddField(
            model_name='linha',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.setor'),
        ),
        migrations.AddField(
            model_name='subcomponente',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.setor'),
        ),
    ]
