# Generated by Django 5.0.1 on 2024-07-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipamento', '0003_area_setor_linha_setor_subcomponente_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='setor',
        ),
        migrations.AddField(
            model_name='area',
            name='setor',
            field=models.ManyToManyField(blank=True, to='accounts.setor'),
        ),
    ]
